all_files_in_repos :=          Makefile autoload/textobj/user.vim doc/textobj-user.txt test/plugin.expected test/plugin.input
current_branch := master
origin_name := origin
origin_uri := ../.
repos_name := vim-textobj-user
version := 0.3.9
